### PR TITLE
Update to newest rustc

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
I'm not sure how to fix `trie`. Errors:

    collect/src/trie/map.rs:538:52: 538:75 error: type `&[trie::map::TrieNode<T>; 16]` does not implement any method in scope named `slice_from_or_fail`
    collect/src/trie/map.rs:538                     it.stack[it.length] = children.$slice_from(&slice_idx).$iter();
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~
    collect/src/trie/map.rs:538:52: 538:75 error: type `&mut [trie::map::TrieNode<T>; 16]` does not implement any method in scope named `slice_from_or_fail_mut`
    collect/src/trie/map.rs:538                     it.stack[it.length] = children.$slice_from(&slice_idx).$iter();
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by tbu-** [comment]
Feel free to take this as a starting point for fixing `trie` erros.

**Comment by huonw** [comment]
Use slicing syntax `x[a..]`. This doesn't need to be specific about mutability any more either.

**Comment by tbu-** [comment]
@huonw Thanks, I didn't think of that.

**Comment by tbu-** [comment]
Added `#[allow(unstable)]` because it produced a large load of warnings.

**Comment by apasel422** [comment]
@tbu-: Did you run `cargo test` on this? I believe there are some tests that need to be updated for the change to `{:?}`, among other things.

**Comment by tbu-** [comment]
No, I didn't, will try it now.

**Comment by tbu-** [comment]
Everything works except for the doctests, but because they have an inherent `#[deny(unstable)]` right now, but this will be fixed soon.

**Comment by tbu-** [comment]
@Gankro All tests pass now, ready to be merged. Compiles with `rustc 1.0.0-dev (20bce4481 2015-01-09 04:14:53 +0000)` (https://github.com/rust-lang/rust/commit/20bce44810eb5146f609b4362990ef8835e55bb5) and newer.

**Comment by apasel422** [comment]
There hasn't been a nightly build incorporating these changes yet, so it doesn't seem useful to merge at this point.

**Comment by tbu-** [comment]
@apasel422 Can I somehow view the nightlies' commit ID?

**Comment by apasel422** [comment]
If you go to the Travis build's output, it's listed there:
```sh
$ rustc --version
rustc 1.0.0-nightly (ea6f65c5f 2015-01-06 19:47:08 +0000)
$ cargo --version
cargo 0.0.1-pre-nightly (23ed197 2015-01-06 02:37:42 +0000)
```

**Comment by apasel422** [comment]
@tbu-: Looks like a new nightly was finally generated:
```sh
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)
```
You should test this PR on that.

**Comment by tbu-** [comment]
@apasel422 This won't compile due to the default warning level of the lint `unstable` (https://github.com/rust-lang/rust/commit/1f70acbf4c4f345265a7626bd927187d3bfed91f#diff-d6c1a78a970f7c6174f36c924862b879R1634) and the `#[deny(warnings)]` (which was fixed in https://github.com/rust-lang/rust/commit/20bce44810eb5146f609b4362990ef8835e55bb5). I'm not willing to go through all the doctest and add `#[allow(unstable)]` everywhere, as this is only a temporary problem.

**Comment by apasel422** [comment]
@tbu-: Regardless of whether this PR is merged, `collect` won't be usable with today's nightly.

**Comment by Gankro** [comment]
I'll handle the rest locally.
